export const FOLD_SEPARATOR = '\r\n '
export const LINE_SEPARATOR = '\r\n'
export const PARAMETER_SEPARATOR = ';'
export const PARAMETER_KV_SEPARATOR = '='
export const PROPERTY_KV_SEPARATOR = ':'

export const FOLD_REGEX = new RegExp(/.{1,75}/g)

export const PREFIX = 'BEGIN'
export const SUFFIX = 'END'

export const VALUE_TYPES = {
  BINARY: 'BINARY',
  BOOLEAN: 'BOOLEAN',
  CALADDRESS: 'CALADDRESS',
  'CAL-ADDRESS': 'CALADDRESS',
  DATE: 'DATE',
  DATETIME: 'DATETIME',
  'DATE-TIME': 'DATETIME',
  DURATION: 'DURATION',
  FLOAT: 'FLOAT',
  INTEGER: 'INTEGER',
  PERIOD: 'PERIOD',
  RECUR: 'RECUR',
  TEXT: 'TEXT',
  TIME: 'TIME',
  URI: 'URI',
  UTC: 'UTC'
}

export const DEFAULT_VALUE_TYPES = {
  DTSTART: VALUE_TYPES.DATETIME,
  DTEND: VALUE_TYPES.DATETIME,
  DTSTAMP: VALUE_TYPES.DATETIME,
  DUE: VALUE_TYPES.DATETIME,
  VERSION: VALUE_TYPES.FLOAT + '__FIXED_1'
}

